name: Weather Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '17 * * * *'

jobs:
  collect-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Collect hourly weather
        run: curl --fail --show-error --silent --retry 3 "https://topv51.vercel.app/api/weather-hourly"
